services:
  - type: web
    name: telegram-support-bot
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
    plan: free 