services:
  - type: web
    name: telegram-support-bot
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_GROUP_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free 